name: notebook
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- tzdata=2022e=h191b570_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- tblib=1.7.0=pyhd8ed1ab_0
- boost-cpp=1.78.0=h75c5d50_1
- zict=2.2.0=pyhd8ed1ab_0
- postgresql=14.5=hfdbbde3_0
- libcurl=7.85.0=h7bff187_0
- libgfortran5=12.2.0=h337968e_18
- libgdal=3.5.1=h32640fd_1
- xorg-libsm=1.2.3=hd9c2040_1000
- pixman=0.40.0=h36c2ea0_0
- geopandas-base=0.9.0=pyhd8ed1ab_1
- lz4=4.0.0=py310h5d5e884_2
- libiconv=1.17=h166bdaf_0
- fonts-conda-ecosystem=1=0
- c-ares=1.18.1=h7f98852_0
- rtree=1.0.1=py310hbdcdc62_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- pyyaml=6.0=py310h5764c6d_4
- freexl=1.0.6=h166bdaf_1
- xorg-libxau=1.0.9=h7f98852_0
- libdap4=3.20.6=hd7c4107_2
- libgomp=12.2.0=h65d4601_18
- click=8.1.3=py310hff52083_0
- bzip2=1.0.8=h7f98852_4
- dask=2022.10.0=pyhd8ed1ab_2
- libssh2=1.10.0=haa6b8db_3
- ncurses=6.3=h27087fc_1
- cytoolz=0.12.0=py310h5764c6d_0
- libgcc-ng=12.2.0=h65d4601_18
- libxcb=1.13=h7f98852_1004
- pytz=2022.5=pyhd8ed1ab_0
- kealib=1.4.15=hfe1a663_0
- nss=3.78=h2350873_0
- curl=7.85.0=h7bff187_0
- ld_impl_linux-64=2.39=hc81fddc_0
- python_abi=3.10=2_cp310
- libwebp-base=1.2.4=h166bdaf_0
- tzcode=2022e=h166bdaf_0
- cfitsio=4.1.0=hd9d235c_0
- pandas=1.5.1=py310h769672d_0
- attrs=22.1.0=pyh71513ae_1
- geotiff=1.7.1=h4fc65e6_3
- locket=1.0.0=pyhd8ed1ab_0
- libspatialindex=1.9.3=h9c3ff4c_4
- fontconfig=2.14.0=hc2a2eb6_1
- wheel=0.37.1=pyhd8ed1ab_0
- libbrotlidec=1.0.9=h166bdaf_7
- blosc=1.21.1=h83bc5f7_3
- expat=2.4.9=h27087fc_0
- lerc=4.0.0=h27087fc_0
- shapely=1.8.5=py310h5e49deb_0
- freetype=2.12.1=hca18f0e_0
- libkml=1.3.0=h37653c0_1015
- libcblas=3.9.0=16_linux64_openblas
- fonttools=4.37.4=py310h5764c6d_0
- pthread-stubs=0.4=h36c2ea0_1001
- idna=3.4=pyhd8ed1ab_0
- markupsafe=2.1.1=py310h5764c6d_1
- poppler-data=0.4.11=hd8ed1ab_0
- json-c=0.16=hc379101_0
- toolz=0.12.0=pyhd8ed1ab_0
- libspatialite=5.0.1=hd36657c_19
- gdal=3.5.1=py310hce6f0df_1
- pillow=9.2.0=py310hbd86126_2
- bokeh=2.4.3=pyhd8ed1ab_3
- libtiff=4.4.0=h55922b4_4
- libbrotlicommon=1.0.9=h166bdaf_7
- libnghttp2=1.47.0=hdcd2b5c_1
- xerces-c=3.2.4=h55805fa_1
- pyopenssl=22.1.0=pyhd8ed1ab_0
- six=1.16.0=pyh6c4a22f_0
- font-ttf-inconsolata=3.000=h77eed37_0
- xz=5.2.6=h166bdaf_0
- libdeflate=1.14=h166bdaf_0
- pyparsing=3.0.9=pyhd8ed1ab_0
- font-ttf-ubuntu=0.83=hab24e00_0
- contourpy=1.0.5=py310hbf28c38_0
- networkx=2.8.7=pyhd8ed1ab_0
- mapclassify=2.4.3=pyhd8ed1ab_0
- libbrotlienc=1.0.9=h166bdaf_7
- poppler=22.04.0=h0733791_3
- munkres=1.1.4=pyh9f0ad1d_0
- tiledb=2.9.5=h1e4a385_0
- libzip=1.9.2=hc869a4a_1
- fiona=1.8.21=py310h60a68a4_2
- jpeg=9e=h166bdaf_2
- xorg-libice=1.0.10=h7f98852_0
- sqlite=3.39.4=h4ff8645_0
- zlib=1.2.13=h166bdaf_4
- xorg-libxext=1.3.4=h7f98852_1
- xorg-xextproto=7.3.0=h7f98852_1002
- hdf4=4.2.15=h9772cbc_4
- libstdcxx-ng=12.2.0=h46fd767_18
- jinja2=3.1.2=pyhd8ed1ab_1
- libopenblas=0.3.21=pthreads_h78a6416_3
- tk=8.6.12=h27826a3_0
- threadpoolctl=3.1.0=pyh8a188c0_0
- setuptools=65.5.0=pyhd8ed1ab_0
- munch=2.5.0=py_0
- _libgcc_mutex=0.1=conda_forge
- scikit-learn=1.1.2=py310h0c3af53_0
- libnetcdf=4.8.1=nompi_h329d8a1_102
- libnsl=2.0.0=h7f98852_0
- libblas=3.9.0=16_linux64_openblas
- urllib3=1.26.11=pyhd8ed1ab_0
- msgpack-python=1.0.4=py310hbf28c38_0
- proj=9.0.1=h93bde94_1
- libpng=1.6.38=h753d276_0
- xarray=2022.10.0=pyhd8ed1ab_0
- nspr=4.32=h9c3ff4c_1
- keyutils=1.6.1=h166bdaf_0
- readline=8.1.2=h0f457ee_0
- lz4-c=1.9.3=h9c3ff4c_1
- packaging=21.3=pyhd8ed1ab_0
- libsqlite=3.39.4=h753d276_0
- libuuid=2.32.1=h7f98852_1000
- pcre=8.45=h9c3ff4c_0
- libev=4.33=h516909a_1
- gettext=0.21.1=h27087fc_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- matplotlib-base=3.6.1=py310h8d5ebf3_0
- libpq=14.5=hd77ab85_0
- yaml=0.2.5=h7f98852_2
- click-plugins=1.1.1=py_0
- cloudpickle=2.2.0=pyhd8ed1ab_0
- cftime=1.6.2=py310hde88566_0
- scipy=1.9.3=py310hdfbd76f_0
- xorg-libxrender=0.9.10=h7f98852_1003
- brotlipy=0.7.0=py310h5764c6d_1004
- xorg-xproto=7.0.31=h7f98852_1007
- lcms2=2.12=hddcbb42_0
- libgfortran-ng=12.2.0=h69a702a_18
- geos=3.11.0=h27087fc_0
- libxml2=2.10.3=h7463322_0
- netcdf4=1.5.8=nompi_py310hd7ca5b8_101
- hdf5=1.12.1=nompi_h2386368_104
- brotli-bin=1.0.9=h166bdaf_7
- heapdict=1.0.1=py_0
- typing_extensions=4.4.0=pyha770c72_0
- python=3.10.6=h582c2e5_0_cpython
- geopandas=0.9.0=pyhd8ed1ab_1
- openssl=1.1.1q=h166bdaf_1
- xorg-renderproto=0.11.1=h7f98852_1002
- distributed=2022.10.0=pyhd8ed1ab_2
- dask-core=2022.10.0=pyhd8ed1ab_1
- pycparser=2.21=pyhd8ed1ab_0
- giflib=5.2.1=h36c2ea0_2
- pysocks=1.7.1=pyha2e5f31_6
- cycler=0.11.0=pyhd8ed1ab_0
- xorg-libx11=1.7.2=h7f98852_0
- icu=70.1=h27087fc_0
- pcre2=10.37=hc3806b6_1
- pyproj=3.4.0=py310hf94497c_0
- libglib=2.74.0=h7a41b64_0
- cairo=1.16.0=ha61ee94_1014
- krb5=1.19.3=h3790be6_0
- psutil=5.9.3=py310h5764c6d_0
- sortedcontainers=2.4.0=pyhd8ed1ab_0
- certifi=2022.9.24=pyhd8ed1ab_0
- fonts-conda-forge=1=0
- pip=22.3=pyhd8ed1ab_0
- librttopo=1.1.0=hf730bdb_11
- partd=1.3.0=pyhd8ed1ab_0
- cligj=0.7.2=pyhd8ed1ab_1
- libzlib=1.2.13=h166bdaf_4
- libffi=3.4.2=h7f98852_5
- _openmp_mutex=4.5=2_gnu
- snappy=1.1.9=hbd366e4_1
- kiwisolver=1.4.4=py310hbf28c38_0
- cffi=1.15.1=py310h255011f_1
- zstd=1.5.2=h6239696_4
- unicodedata2=14.0.0=py310h5764c6d_1
- liblapack=3.9.0=16_linux64_openblas
- brotli=1.0.9=h166bdaf_7
- numpy=1.23.4=py310h53a5b5f_0
- tornado=6.1=py310h5764c6d_3
- cryptography=38.0.2=py310h597c629_0
- fsspec=2022.10.0=pyhd8ed1ab_0
- openjpeg=2.5.0=h7d73246_1
- libedit=3.1.20191231=he28a2e2_2
- python-dateutil=2.8.2=pyhd8ed1ab_0
- ca-certificates=2022.9.24=ha878542_0
- joblib=1.2.0=pyhd8ed1ab_0
- xorg-kbproto=1.0.7=h7f98852_1002

